# Latent DDPM with Classifier-Free Guidance Config File

# Run name for tracking
run_name: latent-ddpm-cfg-imagenet100

# Random seed for reproducibility
seed: 42

# Dataset path
data_dir: ./data

# Image parameters
image_size: 128
batch_size: 64
num_workers: 8
num_classes: 100

# Training parameters
num_epochs: 100
learning_rate: 1e-4
weight_decay: 1e-6
grad_clip: 1.0

# DDPM parameters
num_train_timesteps: 1000
num_inference_steps: 100
beta_start: 0.0001
beta_end: 0.02
beta_schedule: linear
variance_type: fixed_small
prediction_type: epsilon
clip_sample: true
clip_sample_range: 1.0

# UNet architecture parameters for latent space (smaller network since latents are smaller)
unet_in_size: 32
unet_in_ch: 3
unet_ch: 128
unet_ch_mult: [1, 2, 4, 8]
unet_attn: [1, 2, 3]
unet_num_res_blocks: 2
unet_dropout: 0.1

# Latent DDPM settings
latent_ddpm: true

# Classifier-Free Guidance settings
use_cfg: true
cfg_guidance_scale: 3.0

# DDIM sampler for faster inference
use_ddim: true