run_name: ddpm
seed: 42
data_dir: ./data
image_size: 32
batch_size: 128
num_workers: 10
num_classes: 100
num_epochs: 50
learning_rate: 0.0002
weight_decay: 0.0
num_train_timesteps: 1000
num_inference_steps: 200
beta_start: 0.0001
beta_end: 0.02
beta_schedule: linear

variance_type: fixed_small
predictor_type: epsilon
unet_in_size: 128
unet_in_ch: 3
unet_ch: 128
unet_num_res_blocks: 2
unet_ch_mult: [1, 2, 2, 4]
unet_attn: [2, 3]
unet_dropout: 0.0